volumes:
  vpn-data:

services:
  vpn:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: vpn
    container_name: vpn
    volumes:
      - vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro